### ISSUE TITLE
grunt test:cov is failing

### ISSUE THREAD

**Issue by mattkime** [wycats/handlebars.js#1026]
anyone else seeing this?

```
➜  handlebars.js git:(master) grunt test:cov
Running "test:cov" task
Loading config: /Users/mattk/code/handlebars.js/.istanbul.yml
Running env: ./node
=============================================================================
Writing coverage object [/Users/mattk/code/handlebars.js/coverage/coverage.json]
Writing coverage reports at [/Users/mattk/code/handlebars.js/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 44.01% ( 956/2172 ), 298 ignored
Branches     : 32.86% ( 418/1272 ), 182 ignored
Functions    : 28.24% ( 85/301 ), 22 ignored
Lines        : 43.57% ( 912/2093 )
================================================================================
fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/mattk/code/handlebars.js/spec/mustache/specs/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Suite.<anonymous> (/Users/mattk/code/handlebars.js/spec/spec.js:11:27)
    at context.describe.context.context (/Users/mattk/code/handlebars.js/node_modules/mocha/lib/interfaces/bdd.js:74:10)
    at Object.<anonymous> (/Users/mattk/code/handlebars.js/spec/spec.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/mattk/code/handlebars.js/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by kpdecker** [comment]
You need to init the git submodule that imports those files.

```
git submodule update --init --recursive
```

Should do the trick.

**Comment by mattkime** [comment]
ah, perfect!
