### ISSUE TITLE
Nested inline partials breaks after 3 levels

### ISSUE THREAD

**Issue by michaellopez** [wycats/handlebars.js#1100]
Following up on #1089. I'm loving the inline partials, but do tell me if I'm abusing them :)

Given this test:
```js
it('should support greater than 3 nested levels of inline partials', function() {
    var string = '{{#> sublayout}}{{#*inline "subsubcontent"}}subsubcontent{{>subsubcontent}}{{/inline}}{{/sublayout}}';
    var partials = {
      doctype: 'doctype{{> content}}',
      layout: '{{#> doctype}}{{#*inline "content"}}layout{{> subcontent}}{{/inline}}{{/doctype}}',
      sublayout: '{{#> layout}}{{#*inline "subcontent"}}subcontent{{> subsubcontent}}{{/inline}}{{/layout}}'
    };
    shouldCompileToWithPartials(string, [{}, {}, partials], true, 'doctypelayoutsubcontentsubsubcontent');
  });
```

I get this result:
```shell
Running env: ./runtime

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  475 passing (1s)
  26 pending
  1 failing

  1) Regressions should support greater than 3 nested levels of inline partials:
     Error: The partial subsubcontent could not be found
      at Object.invokePartial (dist/handlebars.runtime.js:1185:12)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.runtime.js:988:40)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (dist/handlebars.runtime.js:1139:13)
      at Object.invokePartial (dist/handlebars.runtime.js:1187:13)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.runtime.js:988:40)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (dist/handlebars.runtime.js:1139:13)
      at Object.invokePartial (dist/handlebars.runtime.js:1187:13)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.runtime.js:988:40)



Running env: ./browser

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․

  575 passing (837ms)
  26 pending
  1 failing

  1) Regressions should support greater than 3 nested levels of inline partials:
     Error: The partial subsubcontent could not be found
      at Object.invokePartial (dist/handlebars.js:1253:12)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.js:1056:40)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (dist/handlebars.js:1207:13)
      at Object.invokePartial (dist/handlebars.js:1255:13)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.js:1056:40)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (dist/handlebars.js:1207:13)
      at Object.invokePartial (dist/handlebars.js:1255:13)
      at Object.invokePartialWrapper [as invokePartial] (dist/handlebars.js:1056:40)



Running env: ./node

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  635 passing (1s)
  26 pending
  1 failing

  1) Regressions should support greater than 3 nested levels of inline partials:
     Error: The partial subsubcontent could not be found
      at Object.invokePartial (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:19064)
      at Object.invokePartialWrapper [as invokePartial] (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:5106)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:15554)
      at Object.invokePartial (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:19351)
      at Object.invokePartialWrapper [as invokePartial] (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:5106)
      at eval (eval at createFunctionContext (.../handlebars.js/dist/cjs/handlebars/compiler/javascript-compiler.js:9:13103), <anonymous>:6:28)
      at prog (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:15554)
      at Object.invokePartial (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:19351)
      at Object.invokePartialWrapper [as invokePartial] (.../handlebars.js/dist/cjs/handlebars/runtime.js:9:5106)
```
@kpdecker Maybe this is a similar fix as in #1089?

**Comment by waynedpj** [comment]
maybe a typo in the line
```javascript
var string = '{{#> sublayout}}{{#*inline "subsubcontent"}}subsubcontent{{>subsubcontet}}{{/inline}}{{/sublayout}}';
```
asking for partial `subsubcontet` instead of `subsubcontent`?   however, i am not able to test it at the moment.

**Comment by michaellopez** [comment]
@waynedpj Yeah, sorry for the typo, but the bug is not due to it. Updated test in original post.

**Comment by kpdecker** [comment]
Thanks for the test case. That use case should be valid. I'll take a look and see if I can figure out what is going on.

**Comment by kpdecker** [comment]
This is a self-referential partial, which will cause an infinite loop:
```
{{#*inline "subsubcontent"}}subsubcontent{{>subsubcontent}}{{/inline}}
```

When I change to:
```
{{#*inline "subsubcontent"}}subsubcontent{{/inline}}
```

The tests pass.

Are you trying to call inline partials in a recursive manner and have some sort of stopping case that aren't reflected by the test? I'm inclined to say that this is unsupported but want to make sure I understand the whole use case that you are trying to achieve.

**Comment by michaellopez** [comment]
@kpdecker Thank you for your invested time. You are correct, the test case is not accurate. I am not trying to do anything recursive. After your feedback and more debugging I've now found the culprit:

I was trying to render `sublayout` as well as render `subsublayout`, meaning two render passes. So the render pass of `sublayout` wanted the partial `subsublayout` but that was not available at that time. Making `sublayout` include `subsublayout` as a block partial fixed it because that allows it to be undefined, then nothing renders. I hope that makes sense.

Anyways I'm closing this as it all works as it should! Great work!
