### ISSUE TITLE
Precompiler isn't respecting --name

### ISSUE THREAD

**Issue by knksmith57** [wycats/handlebars.js#1131]
Maybe I misunderstand the behavior of `--name`, but it appears that the precompiler isn't respecting this option as my exported `Handlebars.templates` key doesn't reflect the value specified.

```
❯ cat simple.hbs
hello world

❯ handlebars --name hello-world simple.hbs
(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['simple.hbs'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "hello world\n";
},"useData":true});
})();
```

The exported `Handlebars.template` property is setting the template key to `simple.hbs` and not `hello-world`.

Can someone please clarify the expected behavior of this option?

Thanks!

```
❯ handlebars --version
4.0.4

❯ node --version
v4.2.1

❯ uname -a
Darwin kbsmith-mac 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

```

**Comment by kpdecker** [comment]
Thanks for the detailed report. Name was intended to allow for providing one when we could not infer one vs. overriding the inferred name. I don't see any reason why we can't do the later behavior if only one input file is defined.

As a work around, for now you should be able to do (I have not tested this so YMMV):

```
cat simple.hbs | handlebars --name hello-world -
```

**Comment by knksmith57** [comment]
@kpdecker thanks for getting back to me!

The command, as provided, doesn't work for me; however, adding the `-i` flag results in the desired output.

```
❯ cat simple.hbs
<p>Hello World</p>

❯ cat simple.hbs | handlebars --name hello-world -

/Users/kbsmith/.nvm/versions/node/v4.2.1/lib/node_modules/handlebars/bin/handlebars:120
    throw err;
    ^
Error: Unable to open template file "-"
    at /Users/kbsmith/.nvm/versions/node/v4.2.1/lib/node_modules/handlebars/dist/cjs/precompiler.js:107:25
    at FSReqWrap.oncomplete (fs.js:82:15)

❯ cat simple.hbs | handlebars --name hello-world -i -
(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['hello-world'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<p>Hello World</p>\n";
},"useData":true});
})();
```

**Comment by nknapp** [comment]
Closing due to inactivity.
