### ISSUE TITLE
Avoid the use of length attribute in custom helpers

### ISSUE THREAD

**Issue by prometheansacrifice** [wycats/handlebars.js#1194]
When I compiled the following code

```

Usage:

{{#condense}}
{{#each usage}}
    {{#cyan}}bower{{/cyan}} {{.}}
{{/each}}
{{/condense}}


Options:

{{#condense}}
{{#each options}}
    {{#yellow}}{{#rpad length="23"}}{{#if shorthand}}{{shorthand}}, {{/if}}{{flag}}{{/rpad}}{{/yellow}} {{description}}
{{/each}}
{{/condense}}

    Additionally all global options listed in 'bower help' are available

Description:

    {{#indent level="4"}}{{description}}{{/indent}}
```

the following exception was observed.

```

/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:759
    hash.values[key] = value;
                     ^

RangeError: Invalid array length
    at Object.assignToHash (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:759:22)
    at Object.compile (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:113:27)
    at Object.compileChildren (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
    at Object.compile (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
    at Object.compileChildren (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
    at Object.compile (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
    at Object.compileChildren (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
    at Object.compile (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
    at compileInput (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:516:53)
    at ret (/Users/prometheansacrifice/development/js/handlebars-ex/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
```

which can be traced to the following line

```
hash.values[key] = value;
```

On logging, I realised 'length` is being set on `hash.values` with the value `"23"`, which threw the RangeError.

Handlebars could prevent the use of reserved keywords in attributes for custom helpers

Handlebars version: 4.0.5

**Comment by kpdecker** [comment]
Is this available on a public repository somewhere that we can run it locally?

**Comment by prometheansacrifice** [comment]
Try this [repo](https://github.com/prometheansacrifice/handlebars-bug-repro)

**Comment by kpdecker** [comment]
Thanks for the report. I've fixed this in master and added a test for it.

**Comment by prometheansacrifice** [comment]
Appreciate it. Thank you too.

**Comment by philippe-granet** [comment]
@kpdecker @nknapp This fix is not reported in branch 3.x or 4.x ?

**Comment by nils4iviews** [comment]
Appearently not. I don't know why my name appears next to the commit 7d5dba42362a58249d64ea7a10b19a2f67018c55. I don't recall anything about it.

I'm not sure if there are any backward-compatibility issues. If not, and if somebody created a PR for 4.x (and 3.x if needed) containing only this commit, I would merge it.

**Comment by nknapp** [comment]
Appearently not. I don't know why my name appears next to the commit 
7d5dba4. I don't recall anything about it.

I'm not sure if there are any backward-compatibility issues. If not, and 
if somebody created a PR for 4.x (and 3.x if needed) containing only 
this commit, I would merge it.

Am 2019-01-17 11:20, schrieb Philippe GRANET:
