### ISSUE TITLE
Nested #if / #each generates TypeError

### ISSUE THREAD

**Issue by davidkellerman** [wycats/handlebars.js#1221]
Here's a short example that generates the error:

```
var handlebars = require('handlebars');

var template = handlebars.compile(
    '{{#each files.primary as |file|}}\n\
    {{{file.oldFile}}} {{{file.newFile}}}\n\
    {{/each}}\n\
    {{#if files.secondary.length}}\n\
    {{#each files.secondary as |file|}}\n\
    {{{file.oldFile}}} {{{file.newFile}}}\n\
    {{/each}}\n\
    {{/if}}');

var config = {
    files: {
        primary: [ { oldFile: 'old.txt', newFile: 'new.txt' } ],
        secondary: [ { oldFile: 'old.txt', newFile: 'new.txt' } ] }
    };

var rslt = template(config);

console.log(rslt);
```

Run in node, it produces this console output:

```
undefined:6
    + ((stack1 = alias1(((stack1 = blockParams[0][0]) != null ? stack1.oldFile : stack1), depth0)) != null ? stack1 : "")
                                              ^

TypeError: Cannot read property '0' of undefined
    at eval (eval at createFunctionContext (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:47)
    at prog (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:34)
    at Object.prog [as fn] (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at Object.eval (eval at createFunctionContext (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:32)
    at main (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/www.nls.com/nodejs/usr-share-nodejs/www/util/printkit-config/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
```

Any of these changes cause the error to go away:
1. Removing the first `#each` clause from the template
2. Removing the `#if` clause from the template
3. Removing the `{{{file.oldFile}}}` expansion from the second `#each` clause, or replacing it with `{{oldFile}}`

Here's a [fiddle](https://jsfiddle.net/j4zo697n/3/) with essentially the same example. The console output reports a slightly different error (in Firefox: TypeError: blockParams is undefined).

**Comment by olehyermokhin** [comment]
Have the same issue, put a comment here - 
https://github.com/wycats/handlebars.js/issues/1250

**Comment by nknapp** [comment]
Related to #1300 ?

**Comment by davidkellerman** [comment]
I ran the example again. Fails with 4.0.5; succeeds with 4.0.6. Thanks!
