### ISSUE TITLE
Using @partial-block twice in a template not possible

### ISSUE THREAD

**Issue by Dangoo** [wycats/handlebars.js#1252]
I discovered that my issue with #1185 is caused by including the `@partial-block` twice inside a template like this:

**template.hbs**

``` handlebars
<p>
    Me: "{{> @partial-block }}", <br />
    Echo: "{{> @partial-block }}"
</p>
```

**demo.hbs**

``` handlebars
<div>
    {{#> template}}
        Hello echo!
    {{/template}}
</div>
```

Currently no possibility to check, but haven't touched  the code and with with v4.0.3 it seemed to work, however after commit 7535e48 it produces the following console output:

``` bash
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: The partial @partial-block could not be found
    at Object.invokePartial (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:255:11)
    at Object.invokePartialWrapper [as invokePartial] (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:65:39)
    at Object.eval (eval at createFunctionContext (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:252:23), <anonymous>:14:28)
    at main (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:170:32)
    at Object.ret (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:12)
    at Object.lsg-demo-section (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:21)
    at Object.invokePartialWrapper [as invokePartial] (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:69:46)
    at eval (eval at createFunctionContext (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:252:23), <anonymous>:5:31)
    at prog (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/runtime.js:206:12)
    at execIteration (<PROJEKT_ROOT>/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:42:19)
```

/cc @lawnsea

**Comment by nknapp** [comment]
I can confirm that it works with 4.0.3 and 4.0.4, but not in 4.0.5 and 4.0.6

**Comment by nknapp** [comment]
The following functions are called before the exception occurs:

With the template being `{{#> dude}}success{{/dude}}`
and the partial `dude` being `{{> @partial-block }} {{> @partial-block }}`
the function `invokePartialWrapper` is called with the following `options.name` and `options.data`:

```
invokePartialWrapper(
    options.name=dude, 
    options.data={ root: {} }
)
invokePartialWrapper(
    options.name=@partial-block,
    options.data={ root: {}, _parent: { root: {} }, 'partial-block': { [Function: prog] program: 1, depth: 0, blockParams: 0 } }
)
invokePartialWrapper(
    options.name=@partial-block
    options.data={ root: {}, _parent: { root: {} }, 'partial-block': [Function: noop] }
)
```

The last invocation has `options.data['partial-block']` === noop` and that seems to be the problem.

**Comment by Dangoo** [comment]
Nice to hear, thanks @nknapp! Any ideas when the next version containing this will ship?

**Comment by nknapp** [comment]
I can't do that myself (I don't have publish rights for Handlebars on the various registries).

I'll open an issue for that.
