### ISSUE TITLE
RangeError: Invalid string length 

### ISSUE THREAD

**Issue by guilhotarras** [wycats/handlebars.js#1283]
This error is coming up to me when I try to embedd a base64 image on the html template.
The string length of this image is huge (71520000 chars)

My code is this

`var handlebars = require('handlebars');
        var source = fs.readFileSync('features/support/compareResultTemplate.html').toString();
        var template = handlebars.compile(source);
        var result = template(this.valuesForSteps["resultsBuffer"]);`

Where this.valuesForSteps["resultsBuffer"] is an object that has values from base64 images, to embedd on the html.

The error is this:

`RangeError: Invalid string length
         at execIteration (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:17)
         at Object.each (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
         at Object.<anonymous> (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/helpers/block-helper-missing.js:22:33)
         at eval (eval at createFunctionContext (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:62)
         at prog (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
         at execIteration (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
         at Array.<anonymous> (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
         at Object.eval (eval at createFunctionContext (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:31)
         at main (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
         at ret (/Users/beckerqa/Documents/cpa-mc-web-api/test_e2e/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
`

**Comment by nknapp** [comment]
If you want to create on large HTML with inlined images, you could try to use substack's [html-inline](https://www.npmjs.com/package/html-inline) to post-process your HTML. I don't think this is something that can be fixed in Handlebars without major conceptual changes.

## About the error

The `RangeError: Invalid string length` is an error thrown by V8. The string that is generated by the template function seems to be too longer.

I've done a short test with the following program: 

```js
var a = 'a';
while (true) {
        a = a + a;
        console.log("length",a.length);
}
```

And the output is 

```
length 2
length 4
length 8
length 16
length 32
length 64
length 128
length 256
length 512
length 1024
length 2048
length 4096
length 8192
length 16384
length 32768
length 65536
length 131072
length 262144
length 524288
length 1048576
length 2097152
length 4194304
length 8388608
length 16777216
length 33554432
length 67108864
length 134217728
/test.js:3
	a = a + a;
	      ^

RangeError: Invalid string length
    at Object.<anonymous> (/test.js:3:8)
```

So for my NodeJS installation, 134217728 chars in a string is still okay, but twice the size will fail. Your image is about half this size, so Node will probably fail if you include it four times. Are you trying to include multiple images of this size in the template? I guess this is just not possible, since Handlebars builds one big string and does not use streams.

**Comment by nknapp** [comment]
I'm going to close this because this is a limitation of the VM, not Handlebars. Please add a comment, if you think it's worth to keep this issue open.
