### ISSUE TITLE
Wildcard expansion on Windows

### ISSUE THREAD

**Issue by marcoscaceres** [wycats/handlebars.js#1318]
I'm wondering, does Handlebars support wildcard expansion on Windows? or am I doing something wrong:

```CMD
> handlebars -a js/geonovum/templates/*.css  -f js/templates.js

C:\Users\marcosc\AppData\Roaming\npm\node_modules\handlebars\bin\handlebars:120
    throw err;
    ^
Error: Unable to open template file "js/geonovum/templates/*.css"
    at C:\Users\marcosc\AppData\Roaming\npm\node_modules\handlebars\dist\cjs\precompiler.js:107:25
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Obviously, the above works fine in Git Bash (and any *nix distro), but fails in cmd.exe. According to the Windows documentation, it's the application's job to do wildcard expansion on Windows.

**Comment by nknapp** [comment]
Would be great, if somebody who is native on Windows could try to fix this. I always have to start my VM and I don't have a complete dev-environment set up there.

**Comment by jonschlinkert** [comment]
depending on the shell, you will probably need to escape the path by wrapping it in quotes. 

try 

```sh
$ handlebars -a "js/geonovum/templates/*.css"  -f js/templates.js
```

**Comment by nknapp** [comment]
Closing due to inactivity.
