### ISSUE TITLE
TypeError: Cannot read property 'parser' of undefined

### ISSUE THREAD

**Issue by waitingcheung** [wycats/handlebars.js#1368]
When using the function [tokenize](https://github.com/wycats/handlebars.js/blob/master/spec/tokenizer.js#L16) with the template ``{{bar}}}}{{/bar}}`` like the following, a TypeError occurs.

```js
tokenize("{{bar}}}}{{/bar}}");
```

The stack trace of the TypeError.
```
file:///path/handlebars.js:1988
	                if (this.yy.parser) {
	                           ^

TypeError: Cannot read property 'parser' of undefined
    at Object.parseError (file:///path/handlebars.js:1988:29)
    at Object.next (file:///path/handlebars.js:2117:34)
    at Object.lex (file:///path/handlebars.js:2121:31)
```

**Comment by nknapp** [comment]
I don't understand your expectations. Throwing an error seems legit to me. I can see that the your error is not a really good one, but the `compile`-method shows a better error (see https://jsfiddle.net/9D88g/130/).

You template is not syntactically correct, because it closes the first `bar`-literal with four brackets instead of two. Did you want to output `}}` inside the `bar`-block?

**Comment by waitingcheung** [comment]
@nknapp Since this template is syntactically incorrect, I expect an error is thrown like how your jsfiddle example shows using the ``compile`` method. However, a TypeError occurs and no error is thrown.

**Comment by nknapp** [comment]
I'm not sure what "compile" does differently, but the function you are referencing is part of a test-case. It is probably not generic enough to throw meaningful exeptions. Could you tell me why you are using this function?

If you need to parse the template without compiling it to JavaScript, I suggest you use the compilter and a visitor as described in https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md#ast-visitor

**Comment by waitingcheung** [comment]
@nknapp I am working on a testing tool and my tool found such an input that can cause a TypeError in your library based on how you test your library. That's why I am using this function from the test case.

**Comment by nknapp** [comment]
Can you use `Handlebars.parse()`: https://jsfiddle.net/9D88g/136/

Or otherwise, what would you like me to do?

**Comment by waitingcheung** [comment]
@nknapp I notice at line 1988 the if condition ``if (this.yy.parser)``. If you change it to ``if (this.yy && this.yy.parser)``, TypeError will not occur and you can get the same error as ``Handlebars.parse()``. Since that part of the code is generated by Jison, do you have any ideas how to fix that?

**Comment by GerHobbelt** [comment]
xref-ing jison issue: https://github.com/zaach/jison/issues/358

**Comment by nknapp** [comment]
Closing due to inactivity and because this is probably an error in jison
