### ISSUE TITLE
webpack handbars loop error

### ISSUE THREAD

**Issue by dajunJS** [wycats/handlebars.js#1410]
This is my webpack..config.js (3.8.1version)
`module: { 
        rules: [
            {
                test: /\.js$/,
                use: {loader: "babel-loader"}, 
                exclude: /node_modules/
            }, 
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract(["css-loader", "postcss-loader"])
            },
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract(['css-loader','sass-loader','postcss-loader'])
            },
            {
                test: /\.hbs$/,
                use: {loader: "handlebars-loader"}
            }
        ]
    },
`
This is my main.js
`var data = {
    "type": "singleOptionList",
    "text": "sfasdfasdfasdfasdf",
    optionList: [
        {"content": "1,aaaa"},
        {"value": "2,bbbb"}
    ]
}
const textTpl = require('./tpl/' + data.type + '_answer/tpl.hbs');
`
$ webpack --progress --profile
Compilation results:
`WARNING in ./src/tpl/singleOptionList_answer/tpl.hbs
Module build failed: Error: Parse error on line 8:
...                {{ #each optionList }}
----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Parser.parseError (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars@4.0.11@handlebars/dist/cjs/handlebars/compiler/parser.js:268:19)
    at Parser.parse (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars@4.0.11@handlebars/dist/cjs/handlebars/compiler/parser.js:337:30)
    at HandlebarsEnvironment.parse (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars@4.0.11@handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at Object.precompile (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars@4.0.11@handlebars/dist/cjs/handlebars/compiler/compiler.js:492:17)
    at HandlebarsEnvironment.hb.precompile (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars@4.0.11@handlebars/dist/cjs/handlebars.js:42:40)
    at compile (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars-loader@1.6.0@handlebars-loader/index.js:172:23)
    at Object.module.exports (/Applications/XAMPP/xamppfiles/htdocs/robot/node_modules/_handlebars-loader@1.6.0@handlebars-loader/index.js:372:4)
 @ ./src/tpl ^\.\/.*_answer\/tpl\.hbs$
 @ ./src/main.js
`
why

**Comment by dajunJS** [comment]
I found the problem and solve it
