### ISSUE TITLE
rendering raw `{` causes exception

### ISSUE THREAD

**Issue by jupe** [wycats/handlebars.js#1507]
## Environment
OS: macOS
Version: `package.json: "handlebars": "^4.1.0",`
Node.js: `10.13.0`

## Description
Using template like this with `raw-helper`from example:
```
{{{{raw-helper}}}}{{{{{/raw-helper}}}}
```
 causes exception:
```
(node:89704) UnhandledPromiseRejectionWarning: Error: Lexical error on line 25. Unrecognized text.
...raw-helper}}}}}{{{{/raw-helper}}}} {{this}}{{/each}}
-----------------------^
    at Parser.parseError (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parseError (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:394:36)
    at Object.next (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:522:33)
    at Object.lex (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:526:30)
    at lex (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:297:36)
    at Parser.parse (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:320:34)
    at HandlebarsEnvironment.parse (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:515:19)
    at ret (/Users/user/project/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:524:18)
    at PlantUmlCodeGenerator._toCode (/Users/user/project/src/index.js:111:17)
```

## Expected behaviour
Rendering single `{` -character.

Is this bug or am I using raw rendering wrong way ? I just want to render single `{` -character..

Note that this is little special use case - I'm trying to render JS source code from template... If somebody know better template engine for that purpose please let me know. So far `handlebars` has been working well for me.

**Comment by jupe** [comment]
rendering seems to work if I add space after `'{'`: 
`{{{{raw-helper}}}}{ {{{{/raw-helper}}}}`
so assuming somewhere is an bug.

**Comment by liqiang372** [comment]
it's not a bug, 5 consecutive curly brackets just confuse lexer what you are trying to do. see [similar question on stackoverflow](https://stackoverflow.com/questions/24943334/simple-way-to-escape-curly-braces)

**Comment by nknapp** [comment]
@jupe I don't know how complex your rendering is. When I started the [graphql-typewriter project](https://github.com/nknapp/graphql-typewriter), I considered using Handlebars, but in the end I didn't. Instead I used ES6 [template literals](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings). That actually worked quite well.

Handlebars itself generates JS code without any template engine (see [javascript-compiler.js](https://github.com/wycats/handlebars.js/blob/4.x/lib/handlebars/compiler/javascript-compiler.js)).

Another possibility would be to use [escodegen](https://github.com/estools/escodegen).

I'm not sure which alternative suites you best. But if you decide to use Handlebars, you should probably deactivate HTML-escaping completely, using `Handlebars.compile(..., { noescape: true })`. Then you don't have to use triple and quadrupel mustaches.

**Comment by jupe** [comment]
@nknapp thanks for useful respond. I've working with [tool](https://github.com/jupe/puml2code) which generates source code from plantuml code and `{` -characters is quite much needed there.

**Comment by nknapp** [comment]
I forgot to mention `swagger-codegen`, which uses Mustache to render Java-Code. (see https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache).

I think those template would also largely work with Handlebars, so it should be possible to use Handlebars to generate your code. You can use `~` as in `{{{{raw-helper~}}}} { {{{{~/raw-helper}}}}` to renders single curly brackets. (see [whitespace-control](https://handlebarsjs.com/expressions.html#whitespace-control)). That is what the StackOverflow link posted by @liqiang372 suggests.
