### ISSUE TITLE
"Cannot convert object to primitive value" when properties are undefined

### ISSUE THREAD

**Issue by SachaG** [wycats/handlebars.js#1568]
I kept getting the error `Cannot convert object to primitive value`, and I finally figured out that it was because I was trying to access an undefined property (e.g. `user.name` when `name` doesn't exist): 

```
TypeError: Cannot convert object to primitive value
  at strict (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:101:75)
  at Object.eval (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:25)
  at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:180:32)
  at ret (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:183:12)
  at ret (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
  at Promise.asyncApply (packages/vulcan:email/lib/server/email.js:172:26)
```

That issue in itself is not hard to fix on my side, but I was just wondering if there was any way to make the resulting error message more explicit and more informative?

**Comment by nknapp** [comment]
Could you please update the jsfiddle at https://jsfiddle.net/50mskbra/ such that it reproduces your issue?

I cannot reproduce it.

I don't get an error message at all by default. In "strict"-mode, there is another error message https://jsfiddle.net/50mskbra/1/
