### ISSUE TITLE
Antora dynamic partial don't work

### ISSUE THREAD

**Issue by mfillion** [wycats/handlebars.js#1630]
Before filing issues, please check the following points first:

- [X] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [X] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [X] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.
******

Hi, 

Sorry, i can't provide a jsfiddle. Sorry for my bad english too.
I'm trying to code a dynamic partial, on Antora Handlebars.

I want to use the var page.module as partial name.
When i try to print 
```
{{ page.module }}
```
it works and return ROOT

When i try to setup the partial with on of these
```
{{> (lookup page 'module') }} 
{{> (lookup . 'page.module') }} 
{{> (lookup . 'module') this.page }}
{{> (lookup . 'module') page }}
```

I have these error 
```
Error: The partial undefined could not be found
    at Object.invokePartial (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:28)
    at main (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as body] (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:10:28)
    at main (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
```

Can you help me please ?

**Comment by nknapp** [comment]
If {{page.module}} works, i believe {{lookup page 'module'}} should work (without the >)
