### ISSUE TITLE
Expression with same name as helper fails

### ISSUE THREAD

**Issue by mlconnor** [wycats/handlebars.js#950]
If you have an expression that has the same name as a helper you've registered it blows chunks.

    var Handlebars = require('handlebars');

    Handlebars.registerHelper("coolHelper", function(options) {
      return "cool-->" + options.fn(this) + "<--cool";
    });

    Handlebars.registerHelper("title", function(options) {
      return options.fn(this);
    });

    var tmpl = Handlebars.compile("{{#coolHelper}}{{title}}{{/coolHelper}}");
    console.log(tmpl({title:'Michael'}));

And the exceptions is...

    /Users//il/tmpl/testbug.js:8
	  return options.fn(this);
			 ^
    TypeError: Object #<Object> has no method 'fn'
	at Object.<anonymous> (/Users//il/tmpl/testbug.js:8:22)
	at Object.eval (eval at <anonymous> (/Users//il/tmpl/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:3:182)
	at Object.prog [as fn] (/Users//il/tmpl/node_modules/handlebars/dist/cjs/handlebars/runtime.js:168:15)
	at Object.console.log.tmpl.title (/Users//il/tmpl/testbug.js:4:34)
	at Object.eval (eval at <anonymous> (/Users//il/tmpl/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:3:278)
	at ret (/Users//il/tmpl/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
	at ret (/Users//il/tmpl/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
	at Object.<anonymous> (/Users//il/tmpl/testbug.js:12:17)
	at Module._compile (module.js:456:26)
	at Object.Module._extensions..js (module.js:474:10)

...but, if you remove the "title" helper you get

    cool-->Hello World<--cool

**Comment by kpdecker** [comment]
Helpers have precedence. If you would like to reference a context value that has the same name as a helper, then you need to use a scoped reference, i.e. `{{./title}}`.

**Comment by mlconnor** [comment]
Thanks Kevin. Much appreciated.
