### ISSUE TITLE
Pre-compiling issue

### ISSUE THREAD

**Issue by sunsetbrew** [wycats/handlebars.js#996]
This may be user error, but when I try to pre-compile the templates I get this.  Is there something I am supposed to do first?

./bin/handlebars -o../test.js ../test.handlebars

module.js:340
    throw err;
          ^
Error: Cannot find module '../dist/cjs/handlebars'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/xt/www/handlebars.js/lib/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by kpdecker** [comment]
Did you install handlebars from npm?

**Comment by sunsetbrew** [comment]
No, what I did was download the GIT repo and proceeded to try to use bin/handlebars.  A little while after writing this, I downloaded it from npm and it worked fine.  I guess I was expecting to be able to run everything out of the repo, but I don't know enough to get it all working as it should.   I will go ahead and close this now.  Thank you. :)
